{"name": "test_failedcase_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <pytestTest.test_login.Test_webmodou object at 0x000002023D436668>\n\n    @pytest.mark.run(order=1)\n    @allure.severity('critical')\n    def test_failedcase_1(self):\n>       assert 0\nE       assert 0\n\ntest_login.py:37: AssertionError"}, "start": 1650032438255, "stop": 1650032438255, "uuid": "a81b1ace-ce39-4bb6-b0ac-ef0682887226", "historyId": "77e43856dcf54cca0f6731432dd67916", "testCaseId": "8d064ca44724c7ce6ad67022165d9e35", "fullName": "test_login.Test_webmodou#test_failedcase_1", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "PC项目后台企业端接口测试用例"}, {"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_webmodou"}, {"name": "host", "value": "LAPTOP-HCLV5M2H"}, {"name": "thread", "value": "24164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}