{"name": "test_failedcase_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <pytestTest.test_login.Test_webmodou object at 0x0000026E07476668>\n\n    @pytest.mark.run(order=2)\n    @allure.severity('critical')\n    def test_failedcase_1(self):\n>       assert 0\nE       assert 0\n\ntest_login.py:37: AssertionError"}, "start": 1650033226135, "stop": 1650033226135, "uuid": "0704d1af-9cb5-4bd5-a877-76725ee060b6", "historyId": "77e43856dcf54cca0f6731432dd67916", "testCaseId": "8d064ca44724c7ce6ad67022165d9e35", "fullName": "test_login.Test_webmodou#test_failedcase_1", "labels": [{"name": "feature", "value": "PC项目后台企业端接口测试用例"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_webmodou"}, {"name": "host", "value": "LAPTOP-HCLV5M2H"}, {"name": "thread", "value": "21252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}