{"name": "test_login_success", "status": "broken", "statusDetails": {"message": "AttributeError: 'list' object has no attribute 'items'", "trace": "cls = _pytest.runner.CallInfo, func = <function call_runtest_hook.<locals>.<lambda> at 0x000002518B359F28>, when = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: \"Callable[[], TResult]\",\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\n        reraise: Optional[\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\n        ] = None,\n    ) -> \"CallInfo[TResult]\":\n        \"\"\"Call func, wrapping the result in a CallInfo.\n    \n        :param func:\n            The function to call. Called without arguments.\n        :param when:\n            The phase in which the function is called.\n        :param reraise:\n            Exception or exceptions that shall propagate if raised by the\n            function, instead of being wrapped in the CallInfo.\n        \"\"\"\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: Optional[TResult] = func()\n\nc:\\program files\\python36\\lib\\site-packages\\_pytest\\runner.py:340: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nc:\\program files\\python36\\lib\\site-packages\\_pytest\\runner.py:261: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n..\\..\\AppData\\Roaming\\Python\\Python36\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n..\\..\\AppData\\Roaming\\Python\\Python36\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n..\\..\\AppData\\Roaming\\Python\\Python36\\site-packages\\pluggy\\manager.py:87: in <lambda>\n    firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\nc:\\program files\\python36\\lib\\site-packages\\_pytest\\runner.py:156: in pytest_runtest_setup\n    item.session._setupstate.setup(item)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <_pytest.runner.SetupState object at 0x000002518ADC1748>, item = <Function test_login_success>\n\n    def setup(self, item: Item) -> None:\n        \"\"\"Setup objects along the collector chain to the item.\"\"\"\n        needed_collectors = item.listchain()\n    \n        # If a collector fails its setup, fail its entire subtree of items.\n        # The setup is not retried for each item - the same exception is used.\n>       for col, (finalizers, exc) in self.stack.items():\nE       AttributeError: 'list' object has no attribute 'items'\n\nc:\\program files\\python36\\lib\\site-packages\\_pytest\\runner.py:488: AttributeError"}, "description": "\n        登录成功\n        :return:\n        ", "start": 1650443748888, "stop": 1650443748888, "uuid": "b96c1e8c-5581-4f9e-a96c-195a461480ce", "historyId": "04e7bad6debc224718aaa28f449da41f", "testCaseId": "ce2211ee2b5c590c09630ff06ad249f2", "fullName": "script.test_login.Test_Weblogin#test_login_success", "labels": [{"name": "feature", "value": "PC项目后台企业端接口测试用例"}, {"name": "story", "value": "登录成功的测试用例"}, {"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Weblogin"}, {"name": "host", "value": "LAPTOP-HCLV5M2H"}, {"name": "thread", "value": "29876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}]}